# Main
site_title: Kendra's Covid Coaches
site_subtitle: 'Helping facilitate vaccination appointments for central Texas'
# site_url: https://www.athenshelpwithcovid.com
# share_image: https://www.helpwithcovid.com/share-image.png

# Site features
features_enabled:
  patient_directory: false
  resources: false
  # office_hours: false
  # success_stories: false

# Closest Texas Cities
closest_cities:
  - Abilene
  - Arlington
  - Amarillo
  - Austin
  - Bastrop
  - Baytown
  - Beaumont
  - Belton
  - Blanco
  - Boerne
  - Brenham
  - Brownsville
  - Bryan
  - Buda
  - Burnet
  - Carrollton
  - Cedar Creek
  - Cedar Park
  - College Station
  - Conroe
  - Corpus Christi
  - Dallas
  - Denton
  - Driftwood
  - Dripping Springs
  - El Paso
  - Elgin
  - Flower Mound
  - Fort Worth
  - Fredericksburg
  - Frisco
  - Galveston
  - Garland
  - Georgetown
  - Giddings
  - Grand Prairie
  - Harlingen
  - Houston
  - Hutto
  - Irving
  - Johnson City
  - Kerrville
  - Killeen
  - Kingsland
  - Kyle
  - La Grange
  - Lago Vista
  - Lakeway
  - Lampasas
  - Laredo
  - League City
  - Leander
  - Liberty Hill
  - Llano
  - Lockhart
  - Longview
  - Lubbock
  - Manor
  - Marble Falls
  - McAllen
  - McKinney
  - Mesquite
  - Midland
  - New Braunfels
  - Odessa
  - Pasadena
  - Pearland
  - Pflugerville
  - Plano
  - Richardson
  - Rockdale
  - Round Rock
  - Rowlett
  - S. Austin
  - San Angelo
  - San Antonio
  - San Marcos
  - Schertz
  - Seguin
  - Smithville
  - Spicewood
  - Spring
  - Sugar Land
  - Taylor
  - Temple
  - The Woodlands
  - Tyler
  - Uvalde
  - Victoria
  - Waco
  - Wimberly
  - N/A - Outside of Texas

# US States
states:
  - Alabama
  - Alaska
  - Arizona
  - Arkansas
  - California
  - Colorado
  - Connecticut
  - Delaware			
  - Florida
  - Georgia
  - Hawaii
  - Idaho
  - Illinois
  - Indiana
  - Iowa
  - Kansas
  - Kentucky		
  - Louisiana		
  - Maine
  - Maryland
  - Massachusetts
  - Michigan
  - Minnesota
  - Mississippi
  - Missouri
  - Montana
  - Nebraska
  - Nevada
  - New Hampshire
  - New Jersey
  - New Mexico
  - New York
  - North Carolina
  - North Dakota
  - Ohio
  - Oklahoma
  - Oregon
  - Pennsylvania
  - Rhode Island
  - South Carolina
  - South Dakota
  - Tennessee
  - Texas
  - Utah
  - Vermont
  - Virginia
  - Washington
  - West Virginia
  - Wisconsin
  - Wyoming

# Travel Radius
travel_rad:
  - '10'
  - '25'
  - '50'
  - '100'
  - Over 100

# These are the skills that patients can have and appointments can request.
eligibility:
  - Healthcare Professionals
  - Teachers and Educators
  - Frontline/Essential Workers
  - Adults over 50
  - Ages 16-49 with chronic illness
  - Ages 16-49, general population

weekdays:
  - Monday
  - Tuesday
  - Wednesday
  - Thurdsay
  - Friday
  - N/A

weekends:
  - Saturday
  - Sunday
  - N/A

times:
  - Mornings
  - Midday
  - Afternoons
  - Evenings
  - N/A


# Availability windows that are suggested to patients
patient_availabilities:
  - '1-2 hours a day'
  - '2-4 hours a day'
  - '4+ hours a day'
  - 'Only on Weekends'
  - 'Full Time'

# Options for how many patients a appointment might request
patients_needed_for_request:
  - '1-10'
  - '10-50'
  - '50-100'
  - '100+'

request_types:
  - E-Learning
  - Help Out Communities
  - Job Placement
  - Other
  - Map Patients To Needs
  - Mental Health
  - News and Information
  - Social Giving

request_statuses:
  - 'Unbooked'
  - 'Booking in progress'
  - 'Booking completed, awaiting patient confirmation'
  - 'Patient Confirmed'
  - 'Completed'

communication_statuses:
  - Texted
  - Emailed
  - Called
  - Left voicemail

# If a appointment has less than N patients
# it can ask to be highlighted.
max_patients_for_highlight_offer: 30

appointment_form_locations:
  - On-Site
  - Remote
  - Driving

appointment_form_categories:
  - Ongoing
  - Internships
  - One-Time
  - Other
  
appointment_locations:
  - name: On-Site
    slug: on-site
    body: In-person patient opportunities
    appointment_types:
      - Job Placement
      - Mental Health
      - Help Out Communities
    color: purple
    image: on-site
  - name: Remote
    slug: remote
    body: Patient opportunities that can be performed remotely and safely from your home
    appointment_types:
      - E-Learning
      - Map Patients To Needs
      - Job Placement
      - Mental Health
      - Help Out Communities
    color: orange
    image: remote
  - name: Driving
    slug: driving
    body: Patient opportunities that require a vehicle
    appointment_types:
      - Job Placement
      - Mental Health
      - Help Out Communities
    color: blue
    image: driving

request_categories:
  - name: Ongoing
    slug: ongoing
    body: Neighbors helping neighbors for periods of 2 weeks or more
    request_types:
      - Job Placement
      - Mental Health
      - Help Out Communities
      - Map Patients To Needs
    color: blue
    image: ongoing
  - name: Internships
    slug: internships
    body: Turn your love of helping others into a career
    request_types:
      - E-Learning
      - Map Patients To Needs
      - Job Placement
      - Mental Health
      - Help Out Communities
    color: blue
    image: internships
  - name: One-Time
    slug: one-time
    body: Patient opportunities requiring less that 2 hours of your time
    request_types:
      - Job Placement
      - Mental Health
      - Help Out Communities
    color: blue
    image: one-time
  - name: Other
    slug: other
    body: Sharing events, news, social giving, and other information
    request_types:
      - News and Information
      - Social Giving
      - E-Learning
      - Map Patients To Needs
      - Job Placement
      - Mental Health
      - Help Out Communities
    color: blue
    image: other

global_announcements:
#  - title: Helpful resources for your appointments
#    sub_title: We wrote a playbook on how to manage patients, had some amazing panels, and gathered some deals for you.
#    cta_text: Browse resources
#    cta_url: /offers

events:
  - title: Private Group Office Hours with Sam Altman
    sub_title: Sam does GOH with three HelpWithCovid teams
    cta_text: View recording
    cta_url: https://drive.google.com/file/d/1RW1WBc0OabPD-qg73e_j8oNjuwhCF53t/view?usp=sharing
  - title: Lean thinking in a Crisis. Live Panel with Eric Ries
    sub_title: Eric is an entrepreneur and the author of the New York Times bestseller The Lean Startup. He is the creator of the Lean Startup methodology, which has become a global movement in business, practiced by individuals and companies around the world.
    cta_text: View recording
    cta_url: https://drive.google.com/a/openai.com/file/d/1r8PBT_h2ZcnyMExV_hx6B7W8-n35BpgE/view?usp=drive_web
  - title: A Global Perspective on Problems Needing Solutions Regarding COVID-19 Response. Live Panel with Ambika Bumb
    sub_title: Ambika is a Health, Science and Technology Advisor focusing on Crisis Management and Strategy
    cta_text: View recording
    cta_url: https://drive.google.com/a/openai.com/file/d/1I3TjGcWQUsoKGP5dbPT7WD244UjDYiXf/view?usp=drive_web
  - title: Rethinking Resumes | Creating Impact in the age of Insta-everything
    sub_title: Jaimie Lynn Craig Feliz, Founder of The Hire Standard and Bay Area search and resume guru gives actionable insights and tactics to influence, connect and ultimately be seen as the expert you are.
    cta_text: View recording
    cta_url: https://drive.google.com/drive/u/0/folders/13GJiASpNx_FLu3DsMN2pDoExaDrE-J8l
  - title: Sourcing a Volunteer Workforce from TeamBlind’s 3.5MM+ Professionals with Kyum Kim
    sub_title: Tuesday, April 21st 12pm-12:30pm PST
    cta_text: View recording
    cta_url: https://drive.google.com/drive/u/0/folders/1tst9ZLbB7hWGgQE7NpI4P3CjtctI7gT2
  - title: Live panel on Philanthropic Fundraising
    sub_title: Jennifer Pisansky has 10 years of experience in philanthropic fundraising and talks about raising from foundations.
    cta_text: View recording
    cta_url: https://openai.zoom.us/rec/share/3dZaM6vJy1NJfp3c2UHkfa8oQL-7T6a82yRN-fsOmkl9jfRS3GPg-L-gS4Y9zJu3
  - title: Live panel on How to Scale Volunteers
    sub_title: Glen Moriarty, founder of 7cups on how he manages 320k patients.
    cta_text: View recording
    cta_url: https://openai.zoom.us/rec/play/vZN-dbuq-m03TNKSsASDAfEtW466J6qs1XQWrvtYxRvmU3QDNVv0NLJGYbffjdiMo1gf68qHVnbe2mOi?continueMode=true
  - title: Live panel on Picking Ideas to Work On
    sub_title: Ivan Gayton, former Head of Mission and Board Member at Doctors without Border, talks about building technology for humanitarian/emergency purposes.
    cta_text: View recording
    cta_url: https://zoom.us/rec/share/5sttA5fAsWxLT6_Nx2-Yd7IEDqfuaaa823JI8_tcyUYSZzIbgvNy717m1UGGegEf
  - title: Live panel on How to Sell and Know Your Audience
    sub_title: ClozeLoop Founders, Hilmon Sorey and Cory Bray, talk about understanding your audience and selling to them.
    cta_text: See slides and recording
    cta_url: https://drive.google.com/drive/u/0/folders/1NATDm5yVsYUo8jRY7svE2fqwm1OwcpMu

upcoming_events:
  - title: Walgreens PFIZER Clinic
    sub_title: 4501 Guadalupe St, Austin, TX 78751
    link_text: Register here
    link: https://www.signupgenius.com/go/20f0d4ba9ab2eaaf85-walgreens6
    month: April
    day: 24-30
    time: 9:30 AM-6:15 PM
  - title: Auro Pharmacy Moderna Clinic
    sub_title: 1139 W Braker Lane STE. 102 Austin, TX 78758
    link_text: Register here
    link: https://www.signupgenius.com/go/10c0c4aada82ea1fdc25-auro
    month: April
    day: 18-23
    time: 9:00 AM-2:00 PM
    
funding_resources:
  - cta_text: YC S2020 Application
    cta_url: https://www.ycombinator.com/apply/
  - cta_text: WeFunder
    cta_url: https://wefunder.com/raise-money
  - cta_text: 80,000 Hours
    cta_url: https://mailtrack.io/trace/link/8c8d1564095e2d5ec067747e4b3a6f862edfc731?url=https%3A%2F%2F80000hours.org%2F2020%2F04%2Fopportunities-to-work-on-covid-19%2F&userId=2861473&signature=3d3d868b7658ace5
  - cta_text: Association of Fundraising Professionals
    cta_url: https://afpglobal.org/
  - cta_text: Covid Accelerator
    cta_url: https://covidaccelerator.com/
  - cta_text: Covid19-Response
    cta_url: https://www.covid19-response.com/
  - cta_text: Plug and Play
    cta_url: https://www.plugandplaytechcenter.com/covid-19/?utm_campaign=Health_Newsletter_May%202019&utm_source=hs_email&utm_medium=email&utm_content=85778878&_hsenc=p2ANqtz-8AHUCNB-yeVfppjjjjE5b9GKQdFVnuA6FcmSMy3uJOVWtyLW2-DVKL6ybPr8AWWk9VRfO2TotPM8zP-ZUxkNmrusZNqw&_hsmi=85779062
  - cta_text: MIT Covid-19 Research
    cta_url: https://computing.mit.edu/computation-support-covid-19
  - cta_text: H.E.L.P
    cta_url: https://www.helpvolunteer.app/

partner_resources:
  - name: AWS
    description: $10,000 in AWS credits for approved appointments. Your appointment must be a corporate entity. Email helpwithcovid@gmail.com
    mail_to: info@sacconect.com
  - name: ClozeLoop
    description: |+
      Complete Sales Effectiveness Assessments for three companies we choose. The Sales Effectiveness Assessment is an evaluation of your company’s sales Strategy, Systems, Staff and Skills aligned with short and long-term revenue goals. The assessment provides a prioritized high-impact roadmap, and clear recommendations for growth.
      $2500 value.
    cta_link: https://clozeloop.typeform.com/to/ccPwVe
  - name: Turtle
    description: 40 hours of freelance engineering help is available for three companies chosen by the Turtle team. Turtle's developer network is currently specialized to React, React Native, iOS and Android. Based on your appointment specs and requirements, Turtle will match you with a highly qualified freelance engineer and you'll have full access to the Turtle platform to work together and manage your appointment. A one hour complimentary product planning session with Turtle's founders will also be available to you.
    cta_link: https://forms.gle/8UaPv6Qjaw8sFBNy9
  - name: Blind
    description: |+
      We are offering promotion at no cost for 4 appointments
      - Support 3 appointments with native advertising
      - Support 1 appointment with sponsored AMA post
    cta_link: https://bit.ly/helpwithcovid_blind

media_kit:
  - name: HWC badges
    description: Badge to add to your launched page to gather more team members for your appointment
    cta_link: https://helpwithcovid.com/HWC-media-kit-badges.zip
  - name: HWC logos and wordmarks
    description: Logos, wordmark and banner for any media coverage about HWC
    cta_link: https://helpwithcovid.com/HWC-media-kit-logos.zip

google_fonts_request: 'Lora&family=Roboto:wght@400;500;700'

resource_links:
  -

homepage_featured_requests_count: 3

list_id: 0c97d3c7b8
